@echo off
echo Starting BotStock system...
echo Checking for node_modules...
if not exist "node_modules\" (
    echo Installing dependencies...
    npm install
)
echo Starting the development server...
npm run dev
pause
